export type Language = "en" | "de" | "es";

const de: Record<string, string> = {
  "About": "Über mich", "Work": "Projekte", "Experience": "Erfahrung", "Contact": "Kontakt", "Let's talk": "Kontakt aufnehmen",
  "Open to meaningful opportunities": "Offen für passende Möglichkeiten", "SENIOR SOFTWARE ENGINEER": "SENIOR SOFTWARE ENGINEER",
  "Building scalable backend systems with Java, Spring Boot, and cloud technologies.": "Ich entwickle skalierbare Backend-Systeme mit Java, Spring Boot und Cloud-Technologien.",
  "View projects": "Projekte ansehen", "Download CV": "Lebenslauf herunterladen", "Currently engineering": "Aktueller Fokus", "Systems that scale": "Skalierbare Systeme",
  "Engineering with context.": "Engineering mit Weitblick.",
  "I'm a Senior Software Engineer with more than 8 years of experience building enterprise software, modernizing legacy systems, and designing scalable backend architectures.": "Ich bin Senior Software Engineer mit mehr als 8 Jahren Erfahrung in der Entwicklung von Unternehmenssoftware, der Modernisierung von Legacy-Systemen und dem Entwurf skalierbarer Backend-Architekturen.",
  "I enjoy solving complex technical problems and creating products with real business impact.": "Ich löse gerne komplexe technische Probleme und entwickle Produkte mit echtem geschäftlichem Mehrwert.",
  "Years experience": "Jahre Erfahrung", "Microservices maintained": "Betreute Microservices", "Database records processed per run": "Verarbeitete Datensätze pro Lauf", "PDFs generated / run": "Generierte PDFs / Lauf", "Internal users": "Interne Nutzer", "Production releases": "Produktiv-Releases",
  "Technical toolkit": "Technologie-Stack", "Depth where it matters.": "Tiefe, wo sie zählt.", "A mature toolkit spanning application code, infrastructure, delivery, and the product surface.": "Ein ausgereifter Stack für Anwendungscode, Infrastruktur, Delivery und Produktoberfläche.",
  "Backend": "Backend", "Frontend": "Frontend", "Cloud & DevOps": "Cloud & DevOps", "Development": "Entwicklung",
  "Built in production.": "In Produktion bewährt.", "Long-term ownership of business-critical platforms—from architectural decisions to the incidents that sharpen them.": "Langfristige Verantwortung für geschäftskritische Plattformen – von Architekturentscheidungen bis zur nachhaltigen Lösung von Incidents.",
  "Senior Software Engineer": "Senior Software Engineer", "Enterprise platforms,": "Unternehmensplattformen,", "modern foundations.": "moderne Grundlagen.",
  "Designing and evolving billing systems that support thousands of internal users—while steadily modernizing Java, delivery infrastructure, and service architecture.": "Konzeption und Weiterentwicklung von Abrechnungssystemen für Tausende interne Nutzer – bei kontinuierlicher Modernisierung von Java, Delivery-Infrastruktur und Servicearchitektur.",
  "Enterprise billing platform": "Enterprise-Abrechnungsplattform", "Java 8 → 21 migrations": "Migrationen von Java 8 → 21", "Kubernetes deployments": "Kubernetes-Deployments", "Architecture design": "Architekturdesign", "Weekly production releases": "Wöchentliche Produktiv-Releases", "Mentoring engineers": "Mentoring von Entwicklern", "Incident resolution": "Incident-Behebung", "SQL optimization": "SQL-Optimierung", "Legacy modernization": "Legacy-Modernisierung",
  "Selected work": "Ausgewähltes Projekt", "Complexity, made useful.": "Komplexität, sinnvoll eingesetzt.", "Selected product and engineering work. Enterprise examples intentionally omit confidential implementation details.": "Ausgewählte Produkt- und Engineering-Arbeit. Vertrauliche Implementierungsdetails werden bewusst nicht dargestellt.",
  "Enterprise systems": "Enterprise-Systeme", "A resilient billing ecosystem designed for high-volume processing, reliable integrations, and weekly production delivery.": "Ein robustes Abrechnungsökosystem für hohe Verarbeitungsvolumen, zuverlässige Integrationen und wöchentliche Produktiv-Releases.", "Case study": "Fallstudie",
  "Open source": "Open Source", "Code in the open.": "Code, offen entwickelt.", "Repository metadata is ready to connect to the GitHub API once your public username is configured.": "Repository-Daten können direkt über die GitHub API eingebunden werden.", "Updated recently": "Kürzlich aktualisiert",
  "How I work": "Arbeitsweise", "Principles over process.": "Prinzipien vor Prozessen.",
  "Clean code": "Sauberer Code", "I optimize for clarity first—software should explain itself to the next engineer.": "Klarheit steht an erster Stelle – Software sollte sich dem nächsten Entwickler selbst erklären.",
  "Scalable architecture": "Skalierbare Architektur", "Pragmatic boundaries, observable systems, and deliberate trade-offs over fashionable complexity.": "Pragmatische Grenzen, beobachtbare Systeme und bewusste Abwägungen statt modischer Komplexität.",
  "Team collaboration": "Teamarbeit", "The best systems emerge from shared context, candid feedback, and collective ownership.": "Die besten Systeme entstehen durch gemeinsamen Kontext, ehrliches Feedback und kollektive Verantwortung.",
  "Mentoring": "Mentoring", "I help engineers grow through thoughtful reviews, pairing, and space to make decisions.": "Ich unterstütze Entwickler durch fundierte Reviews, Pairing und Raum für eigene Entscheidungen.",
  "Continuous learning": "Kontinuierliches Lernen", "Curiosity is part of the job. I keep tools current without chasing every trend.": "Neugier gehört zum Beruf. Ich halte Werkzeuge aktuell, ohne jedem Trend zu folgen.",
  "AI-assisted development": "KI-gestützte Entwicklung", "I use AI as a precise multiplier for exploration, quality, and delivery—not a substitute for judgment.": "Ich nutze KI gezielt für Exploration, Qualität und Delivery – nicht als Ersatz für Urteilsvermögen.",
  "AI playground": "KI-Labor", "Exploring the new layer.": "Die neue Ebene erkunden.", "Practical experiments at the intersection of software craft and modern AI capabilities.": "Praktische Experimente an der Schnittstelle von Software-Handwerk und moderner KI.",
  "Developer tools": "Entwicklerwerkzeuge", "Context-aware helpers for repetitive engineering workflows, code exploration, and faster feedback loops.": "Kontextsensitive Helfer für wiederkehrende Workflows, Codeanalyse und schnellere Feedbackzyklen.", "Automation": "Automatisierung", "Prompt systems": "Prompt-Systeme", "LLM integrations": "LLM-Integrationen", "Code generation": "Codegenerierung", "Prototypes designed around real workflows.": "Prototypen für reale Arbeitsabläufe.",
  "Have a challenge in mind?": "Eine Herausforderung im Kopf?", "Let's build something together.": "Lassen Sie uns gemeinsam etwas entwickeln.", "I'm always open to conversations about thoughtful products, ambitious systems, and strong engineering teams.": "Ich freue mich auf Gespräche über durchdachte Produkte, ambitionierte Systeme und starke Engineering-Teams.", "Email me": "E-Mail senden", "Built with Next.js, Tailwind CSS & Framer Motion.": "Entwickelt mit Next.js, Tailwind CSS & Framer Motion."
};

const es: Record<string, string> = {
  "About": "Sobre mí", "Work": "Proyectos", "Experience": "Experiencia", "Contact": "Contacto", "Let's talk": "Hablemos", "Open to meaningful opportunities": "Abierto a oportunidades interesantes",
  "Building scalable backend systems with Java, Spring Boot, and cloud technologies.": "Construyo sistemas backend escalables con Java, Spring Boot y tecnologías cloud.", "View projects": "Ver proyectos", "Download CV": "Descargar CV", "Currently engineering": "Actualmente desarrollando", "Systems that scale": "Sistemas que escalan",
  "Engineering with context.": "Ingeniería con contexto.", "I'm a Senior Software Engineer with more than 8 years of experience building enterprise software, modernizing legacy systems, and designing scalable backend architectures.": "Soy Senior Software Engineer con más de 8 años de experiencia desarrollando software empresarial, modernizando sistemas legacy y diseñando arquitecturas backend escalables.", "I enjoy solving complex technical problems and creating products with real business impact.": "Disfruto resolviendo problemas técnicos complejos y creando productos con impacto real en el negocio.",
  "Years experience": "Años de experiencia", "Microservices maintained": "Microservicios mantenidos", "Database records processed per run": "Registros procesados por ejecución", "PDFs generated / run": "PDF generados / ejecución", "Internal users": "Usuarios internos", "Production releases": "Despliegues a producción",
  "Technical toolkit": "Stack tecnológico", "Depth where it matters.": "Profundidad donde importa.", "A mature toolkit spanning application code, infrastructure, delivery, and the product surface.": "Un stack sólido que abarca código, infraestructura, entrega y experiencia de producto.", "Development": "Desarrollo",
  "Built in production.": "Construido en producción.", "Long-term ownership of business-critical platforms—from architectural decisions to the incidents that sharpen them.": "Responsabilidad a largo plazo sobre plataformas críticas, desde decisiones de arquitectura hasta resolución de incidentes.", "Enterprise platforms,": "Plataformas empresariales,", "modern foundations.": "bases modernas.",
  "Designing and evolving billing systems that support thousands of internal users—while steadily modernizing Java, delivery infrastructure, and service architecture.": "Diseño y evolución de sistemas de facturación para miles de usuarios internos, modernizando Java, la infraestructura de entrega y la arquitectura de servicios.",
  "Enterprise billing platform": "Plataforma de facturación empresarial", "Java 8 → 21 migrations": "Migraciones Java 8 → 21", "Kubernetes deployments": "Despliegues en Kubernetes", "Architecture design": "Diseño de arquitectura", "Weekly production releases": "Despliegues semanales", "Mentoring engineers": "Mentoría de desarrolladores", "Incident resolution": "Resolución de incidencias", "SQL optimization": "Optimización SQL", "Legacy modernization": "Modernización legacy",
  "Selected work": "Proyecto destacado", "Complexity, made useful.": "Complejidad convertida en valor.", "Selected product and engineering work. Enterprise examples intentionally omit confidential implementation details.": "Trabajo seleccionado de producto e ingeniería. Los ejemplos empresariales omiten deliberadamente detalles confidenciales.", "Enterprise systems": "Sistemas empresariales", "A resilient billing ecosystem designed for high-volume processing, reliable integrations, and weekly production delivery.": "Un ecosistema de facturación resiliente diseñado para grandes volúmenes, integraciones fiables y entregas semanales a producción.", "Case study": "Caso de estudio",
  "Open source": "Código abierto", "Code in the open.": "Código en abierto.", "Repository metadata is ready to connect to the GitHub API once your public username is configured.": "Los metadatos de los repositorios están preparados para conectarse a la API de GitHub.", "Updated recently": "Actualizado recientemente",
  "How I work": "Cómo trabajo", "Principles over process.": "Principios antes que procesos.", "Clean code": "Código limpio", "I optimize for clarity first—software should explain itself to the next engineer.": "Priorizo la claridad: el software debería explicarse por sí mismo al siguiente desarrollador.", "Scalable architecture": "Arquitectura escalable", "Pragmatic boundaries, observable systems, and deliberate trade-offs over fashionable complexity.": "Límites pragmáticos, sistemas observables y decisiones conscientes frente a complejidad innecesaria.", "Team collaboration": "Colaboración", "The best systems emerge from shared context, candid feedback, and collective ownership.": "Los mejores sistemas nacen del contexto compartido, feedback honesto y responsabilidad colectiva.", "Mentoring": "Mentoría", "I help engineers grow through thoughtful reviews, pairing, and space to make decisions.": "Ayudo a otros desarrolladores a crecer mediante revisiones, pairing y autonomía para decidir.", "Continuous learning": "Aprendizaje continuo", "Curiosity is part of the job. I keep tools current without chasing every trend.": "La curiosidad forma parte del trabajo. Mantengo mis herramientas al día sin perseguir cada tendencia.", "AI-assisted development": "Desarrollo asistido por IA", "I use AI as a precise multiplier for exploration, quality, and delivery—not a substitute for judgment.": "Utilizo la IA para potenciar exploración, calidad y entrega, no para sustituir el criterio profesional.",
  "AI playground": "Laboratorio de IA", "Exploring the new layer.": "Explorando una nueva capa.", "Practical experiments at the intersection of software craft and modern AI capabilities.": "Experimentos prácticos entre la ingeniería de software y las capacidades modernas de IA.", "Developer tools": "Herramientas para desarrolladores", "Context-aware helpers for repetitive engineering workflows, code exploration, and faster feedback loops.": "Asistentes con contexto para tareas repetitivas, exploración de código y ciclos de feedback más rápidos.", "Automation": "Automatización", "Prompt systems": "Sistemas de prompts", "LLM integrations": "Integraciones LLM", "Code generation": "Generación de código", "Prototypes designed around real workflows.": "Prototipos diseñados para flujos de trabajo reales.",
  "Have a challenge in mind?": "¿Tienes un reto en mente?", "Let's build something together.": "Construyamos algo juntos.", "I'm always open to conversations about thoughtful products, ambitious systems, and strong engineering teams.": "Siempre estoy abierto a conversar sobre productos bien pensados, sistemas ambiciosos y grandes equipos de ingeniería.", "Email me": "Escríbeme", "Built with Next.js, Tailwind CSS & Framer Motion.": "Creado con Next.js, Tailwind CSS y Framer Motion."
};

export function translate(text: string, language: Language) {
  if (language === "de") return de[text] ?? text;
  if (language === "es") return es[text] ?? text;
  return text;
}
